// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuWZQbJGMvWj_v5IH7TfObY58La9W1ODI',
    appId: '1:239970483650:web:9a25144036c5751c7daa5b',
    messagingSenderId: '239970483650',
    projectId: 'agendacentury-343cb',
    authDomain: 'agendacentury-343cb.firebaseapp.com',
    storageBucket: 'agendacentury-343cb.firebasestorage.app',
    measurementId: 'G-ZBCN4J5BW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKBRLLtoqUbaasUawe5Wbh2CIIOiuc0o',
    appId: '1:239970483650:android:aa594176441ba0977daa5b',
    messagingSenderId: '239970483650',
    projectId: 'agendacentury-343cb',
    storageBucket: 'agendacentury-343cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Xhu1y6tJkTRbpj33UdO4NfmPvEoOmVQ',
    appId: '1:239970483650:ios:937e77be35b75c407daa5b',
    messagingSenderId: '239970483650',
    projectId: 'agendacentury-343cb',
    storageBucket: 'agendacentury-343cb.firebasestorage.app',
    iosBundleId: 'com.lmbibbo.agendaCentury',
  );
}
