// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU76EITQoNd5c4S3HjJhfTW1eJ8LmP1eU',
    appId: '1:722020952500:web:af73e1d7e6dfcc6871eae1',
    messagingSenderId: '722020952500',
    projectId: 'centurysalas',
    authDomain: 'centurysalas.firebaseapp.com',
    storageBucket: 'centurysalas.firebasestorage.app',
    measurementId: 'G-WPLTD6KNR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGlUtbgvx-a40pf1VB_rmNQ5mav9qRUI',
    appId: '1:722020952500:android:3529ac083c3b2a7271eae1',
    messagingSenderId: '722020952500',
    projectId: 'centurysalas',
    storageBucket: 'centurysalas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnkU__cghBjASAVFIcy2JE36vPiLaADk',
    appId: '1:722020952500:ios:73e8c18e24b6288371eae1',
    messagingSenderId: '722020952500',
    projectId: 'centurysalas',
    storageBucket: 'centurysalas.firebasestorage.app',
    iosClientId: '722020952500-h6cufs73jnsdproilt6m5gv7ti9k1cbu.apps.googleusercontent.com',
    iosBundleId: 'com.lmbibbo.agendaCentury',
  );

}